# Generated by Django 5.1.7 on 2025-03-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisper_pyannote", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="diarization",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="trasncription",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
