# Generated by Django 5.1.7 on 2025-03-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisper_pyannote", "0003_alter_audiofile_trasncription"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trasncription", models.JSONField(blank=True, null=True)),
                ("diarization", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
