# Generated by Django 5.1.7 on 2025-03-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whisper_pyannote", "0004_audioinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiofile",
            name="diarization",
        ),
        migrations.RemoveField(
            model_name="audiofile",
            name="trasncription",
        ),
    ]
