# Generated by Django 5.1.7 on 2025-03-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whisper_pyannote", "0005_remove_audiofile_diarization_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audioinfo",
            old_name="trasncription",
            new_name="transcription",
        ),
    ]
