# Generated by Django 5.1.7 on 2025-03-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whisper_pyannote", "0006_rename_trasncription_audioinfo_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioinfo",
            name="file_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
